site_name: oersted 
site_url: https://retkins.github.io/oersted
theme: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 1
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav: 
  - "About oersted": index.md
  - "Getting Started": getting-started.md
  - "Examples": 
    - "Force on a Magnetized Sphere": magnetized-sphere.md
  - "Python API": python-api.md
  - "Rust API": "https://docs.rs/oersted/latest/oersted/"