site_name: oersted 
site_url: https://retkins.github.io/oersted
theme: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 1
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav: 
  - "About oersted": index.md
  - "Getting Started": getting-started.md
  - "Examples": 
    - "Force on a Magnetized Sphere": examples/magnetized-sphere.md
    - "Two Magnetized Spheres": examples/two-spheres.md
  - "Theory Reference": theory-reference.md
  - "Python API": python-api.md
  - "Rust API": "https://docs.rs/oersted/latest/oersted/"
  - "References": references.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css