//! Functions and data structures for aggregating physics data at nodes

use crate::{
    octree::{INVALID_NODE, Topology},
    types::{Mat3, Vec3},
};

// Aggregated moments at each level of the octree
//
// Expansion centers are about the node geometric centroids
#[derive(Debug)]
pub struct TreeMoments {
    monopole: Vec<Vec3>, // J*V summed from childen nodes
    dipole: Vec<Mat3>,   // sum_e [Ve * Jie * (rje * cj)]
}

// Compute the monopole and dipole moments generated by the individual element
// sources within a leaf node
#[inline]
fn leaf_moments(
    node_centroid: &Vec3,      // Geometry center of the leaf node
    source_range: (u32, u32),  // Indices into sorted sources
    source_vectors: &[Vec3],   // J or M at each element (sorted)
    source_volumes: &[f64],    // Volume of each element (sorted)
    source_centroids: &[Vec3], // Centroid location of each element (sorted)
) -> (Vec3, Mat3) {
    // Define the expansion center (geometric center of leaf node),
    // the monopole moment contribution, and the dipole moment contribution
    let c: Vec3 = *node_centroid;
    let mut mm: Vec3 = Vec3::default();
    let mut dm: Mat3 = Mat3::default();

    for e in source_range.0 as usize..source_range.1 as usize {
        let sv: Vec3 = source_vectors[e] * source_volumes[e];

        // Monopole contribution is a simple sum
        mm += sv;

        // Dipole contribution about the expansion center
        // M[i,j] += V * J[i] * (r[j] - c[j])
        for im in 0..3 {
            for jm in 0..3 {
                dm.0[im][jm] += sv[im] * (source_centroids[e][jm] - c[jm]);
            }
        }
    }

    (mm, dm)
}

impl TreeMoments {
    pub fn new(n: usize) -> Self {
        Self {
            monopole: vec![Vec3::default(); n],
            dipole: vec![Mat3::default(); n],
        }
    }
    // Update source moments in the tree
    // Note: source vectors must be sorted prior to calling this function!
    pub fn update_moments(
        &mut self,
        source_vectors: &[Vec3], // jdensity or magnetization
        source_volumes: &[f64],  // of the individual source elements
        source_centroids: &[Vec3],
        topology: &Topology,
    ) {
        // Define some notation for simplifying the formulae below
        // ni: index of a node
        // c: centroid of a node
        // e: index of an individual source element (tet4)
        // m: monopole contribution of an element or child node to the parent
        //    note: this is NOT the antisymmetric dipole correction!

        // Nodes at the end are generally leaves, so we start there
        for ni in (0..topology.len()).rev() {
            if topology.is_leaf[ni] {
                let source_range = topology.source_range[ni];
                let (mm, dm) = leaf_moments(
                    &topology.centroids[ni],
                    source_range,
                    source_vectors,
                    source_volumes,
                    source_centroids,
                );

                self.monopole[ni] = mm;
                self.dipole[ni] = dm;
            } else {
                // Sum from the child nodes
                for ci in topology.children[ni] {
                    if ci == INVALID_NODE {
                        continue;
                    }
                    let child = ci as usize;
                    // Monopole contribution is a simple sum
                    let mm: Vec3 = self.monopole[child];
                    self.monopole[ni] += mm;

                    // Dipole contribution requires a bit of extra math
                    let d: Vec3 = topology.centroids[child] - topology.centroids[ni];
                    let dm: Mat3 = self.dipole[child] + Mat3::outer(mm, d);
                    self.dipole[ni] = self.dipole[ni] + dm;
                }
            }
        }
    }
}
