//! Functions and data structures for aggregating physics source data (moments) at
//! octree nodes
//! 
//! # Terminology
//! 
//! Scalars and vectors are represented by lower case variables, tensors by upper-case
//! variables.
//! 
//! ## Elemental values
//! * element (e): individual source 4-node tetrahedral element which may have either a
//!   current density vector or a magnetization vector (or both) associated with it 
//! * volume (v_e): volume of an individual tet4 element 
//! * source vector (s_e): either the j or m vector associated with the element
//! * element location (r_e): vector, location of the element centroid in 3d space
//! * element extent (rho_e): distance from the element centroid to the furthest node
//! 
//! ## Octree nodal values
//! * node (ni): a node of the octree, which may be a branch node (has child nodes 
//!   which are also octree nodes), or a leaf node (has childen which are elements)
//! * nodal expansion center (c): vector,
//!     c = sum_e [|s_e| * v_e * r_e] / sum_e [ |s_e| * v_e]
//!   defines the centroid at which the multipole moment is taken about; similar in 
//!   concept to a mass centroid. The magnitude of the source vector is used to 
//!   weight the centroid. If the elements in the node all have zero moment, then the 
//!   volume of the elements is used to weight the centroids instead.
//! * monopole moment ("point source") (p): vector, p = sum_e [s_e * s_e], the
//!   first-order approximation of the field source, defined at an octree node. This is
//!   a simple summation of the source vector multiplied by the volume of every element
//! * dipole moment (D): 3x3 tensor, D[i,j] = sum_e [v_e * s_e[i] * (r_e[j] - c[j])]
//!   taken about the expansion center of the node 
//! * weight (w): w = sum_e [ |s_e| * v_e ]
//!   unsigned moment weight, used for a coherence check on opening the node 
//! * source extent about expansion center (bmax): 
//!     bmax = max_e [ |r_e - c| + rho_e ] 
//!   max over all elements in the node's full subtree, which defines how large the 
//!   node is for Warren-Salmon acceptance criteria:
//!     accept node if bmax < theta * (d - rho_t)
//!   where rho_t is the extent radius of the collection of targets

use crate::{
    octree::{INVALID_NODE, Topology},
    types::{Mat3, Vec3},
};

// Aggregated moments at each level of the octree
//
// Expansion centers are moment-weighted
#[derive(Debug)]
pub struct TreeMoments {
    pub monopole: Vec<Vec3>,    // J*V summed from childen nodes
    pub dipole: Vec<Mat3>,      // sum_e [Ve * Jie * (rje - cj)]
    pub centers: Vec<Vec3>,     // sum_e [|J_e|*V_e] * r_e] / sum_e [|J|*V_e]; fallback to volume-weighted sum if sum_e [J_e] is zero
    pub weights: Vec<f64>,      // Unsigned moment weight 
    pub bmax: Vec<f64>          // distance from expansion center to further child (node, or element for leaves)
}

// Compute the unsigned weight and moment-weighted center of a leaf node's elements
// Note: the centroid is not predivided by w, saving 3 divides in the case when 
// centroids should not be updated (during an iterative solve)
#[inline]
fn leaf_weight_and_center(
    source_range: (u32, u32),
    source_vectors: &[Vec3],
    source_volumes: &[f64],
    source_centroids: &[Vec3]
) -> (f64, Vec3) {

    let mut w: f64 = 0.0; 
    let mut cw: Vec3 = Vec3::default();

    for e in source_range.0 as usize..source_range.1 as usize {
        let w_e: f64 = source_vectors[e].mag() * source_volumes[e];
        let r: Vec3 = source_centroids[e];
        cw += r * w_e;
        w += w_e;
    }

    (w, cw)
}


// Compute the monopole and dipole moments generated by the individual element
// sources within a leaf node
#[inline]
fn leaf_moments(
    node_centroid: &Vec3,      // Geometry center of the leaf node
    source_range: (u32, u32),  // Indices into sorted sources
    source_vectors: &[Vec3],   // J or M at each element (sorted)
    source_volumes: &[f64],    // Volume of each element (sorted)
    source_centroids: &[Vec3], // Centroid location of each element (sorted)
) -> (Vec3, Mat3) {
    // Define the expansion center (geometric center of leaf node),
    // the monopole moment contribution, and the dipole moment contribution
    let c: Vec3 = *node_centroid;
    let mut p: Vec3 = Vec3::default();
    let mut dm: Mat3 = Mat3::default();

    for e in source_range.0 as usize..source_range.1 as usize {
        let sv: Vec3 = source_vectors[e] * source_volumes[e];

        // Monopole contribution is a simple sum
        p += sv;

        // Dipole contribution about the expansion center
        // M[i,j] += V * J[i] * (r[j] - c[j])
        for im in 0..3 {
            for jm in 0..3 {
                dm.0[im][jm] += sv[im] * (source_centroids[e][jm] - c[jm]);
            }
        }
    }

    (p, dm)
}

impl TreeMoments {
    pub fn new(n: usize) -> Self {
        Self {
            monopole: vec![Vec3::default(); n],
            dipole: vec![Mat3::default(); n],
            centers: vec![Vec3::default(); n], 
            weights: vec![0.0; n],
            bmax: vec![0.0; n]
        }
    }

    /// Update source moment data in the tree
    /// 
    /// Note: source vectors must be sorted prior to calling this function!
    ///
    /// This function does the following:
    /// 1. Updates monopole moments (J*V or M*V) and moment-weighted expansion centers
    ///  as a top-down pass on the tree
    /// 3. Computes dipole moment corrections, as a bottom-up pass on the tree, as they
    ///    require knowledge of the expansion centers 
    pub fn update(
        &mut self,
        source_vectors: &[Vec3], // jdensity or magnetization
        source_volumes: &[f64],  // of the individual source elements
        source_centroids: &[Vec3],
        source_extents: &[f64],
        topology: &Topology,
        recompute_centers: bool       // set this flag to false only for iterative transient solves (future work)
    ) {
        // Define some notation for simplifying the formulae below
        // ni: index of a node
        // c: centroid of a node
        // e: index of an individual source element (tet4)
        // m: monopole contribution of an element or child node to the parent
        //    note: this is NOT the antisymmetric dipole correction!

        // Nodes at the end are generally leaves, so we start there
        for ni in (0..topology.len()).rev() {
            if topology.is_leaf[ni] {
                let source_range = topology.source_range[ni];

                // Node weight and center 
                let (w, cw) = leaf_weight_and_center(
                    source_range, 
                    source_vectors, 
                    source_volumes, 
                    source_centroids
                );
                self.weights[ni] = w;

                if recompute_centers {
                    self.centers[ni] = if w > 0.0 {
                        cw/w
                    }
                        else {
                            topology.centroids[ni]
                        
                    };
                }

                let (p, dm) = leaf_moments(
                    &self.centers[ni],
                    source_range,
                    source_vectors,
                    source_volumes,
                    source_centroids,
                );

                self.monopole[ni] = p;
                self.dipole[ni] = dm;

            } else {
                // Compute the weight and centroid of the child nodes separately, 
                // before computing the moments
                let mut w: f64 = 0.0; 
                let mut cw: Vec3 = Vec3::default();

                for ci in topology.children[ni] {
                    if ci == INVALID_NODE {
                        continue;
                    }
                    let child = ci as usize;
                    w += self.weights[child];
                    cw += self.centers[child] * self.weights[child];
                }
                self.weights[ni] = w;

                if recompute_centers {
                    self.centers[ni] = if w > 0.0 {
                        cw/w
                    }
                        else {
                            topology.centroids[ni]
                        
                    };
                }

                let c: Vec3 = self.centers[ni];
                let mut p = Vec3::default();
                let mut dm = Mat3::default();

                for ci in topology.children[ni] {
                    if ci == INVALID_NODE {
                        continue;
                    }
                    let child = ci as usize;

                    // Monopole contribution is a simple sum
                    let pc: Vec3 = self.monopole[child];
                    p += pc;

                    // Dipole contribution requires a bit of extra math
                    let d: Vec3 = self.centers[child] - c;
                    dm = dm + self.dipole[child] + Mat3::outer(pc, d);
                }
                self.monopole[ni] = p;
                self.dipole[ni] = dm;
            }
        }

        if recompute_centers {
            // Compute the extent radius of a node in a top-down pass over the tree
            for ni in 0..topology.len() {
                let c = self.centers[ni];
                let source_range = topology.source_range[ni];
                let mut b: f64 = 0.0; 
                for e in source_range.0 as usize..source_range.1 as usize {
                    let d = (source_centroids[e] - c).mag();
                    let rho = d + source_extents[e];
                    b = b.max(rho);
                }
                self.bmax[ni] = b;
            }
        }
    }
}
