//! Solver kernels for evaluating the magnetic fields generated by octree nodes, which
//! are aggregated from individual source elements.

#![allow(non_snake_case)]

use crate::{
    INV_4PI, MU0, MU0_4PI,
    biotsavart::{IntegrationMethod, Kernel, RequestedField, SourceVectors, select_kernel},
    check_lengths,
    octree::Source,
    types::{Mat3, Vec3},
};

/// Define a multipole expansion order for the solver
#[derive(Clone, Copy, Debug)]
pub enum MultipoleOrder {
    Monopole,
    Dipole,
    // Quadrupole, // TODO: implement in future release
}

impl MultipoleOrder {
    /// Select a multipole order (for Python bindings)
    /// 0 -> Monopole, 1 -> Dipole
    /// Defaults to monopole order
    pub fn from_int(order: u32) -> Self {
        match order {
            1 => Self::Dipole,
            // 2 => Self::Quadrupole,   // TODO: implement in future release
            _ => Self::Monopole, // Default to monopole order
        }
    }
}

/// Contains all components of the multipole expansion for the kernel to
/// operate on
///
/// These components are always computed during octree construction and update, because
/// they are cheap relative to the solve and it simplifies the logic tremendously
pub struct MultipoleExpansion<'a> {
    pub c: &'a Vec3, // expansion center
    pub p: &'a Vec3, // Monopole term
    pub D: &'a Mat3, // Dipole term
}

// Node centroid, monopole, dipole, targets, out
pub type FarKernel =
    fn(MultipoleExpansion, (&[f64], &[f64], &[f64]), (&mut [f64], &mut [f64], &mut [f64]));

pub fn select_near_kernel(
    field: RequestedField,
    source: Source,
    method: IntegrationMethod,
) -> Kernel {
    // TODO: make this not require a vec internally
    let src_vectors = match source {
        Source::CurrentDensity => SourceVectors::CurrentDensity(&[Vec3::default()]),
        Source::Magnetization => SourceVectors::Magnetization(&[Vec3::default()]),
    };
    select_kernel(field, &src_vectors, method)
}

pub fn select_far_kernel(
    field: RequestedField,
    source: Source,
    order: MultipoleOrder,
) -> FarKernel {
    match (field, source, order) {
        (RequestedField::AField, Source::CurrentDensity, MultipoleOrder::Monopole) => {
            a_current_node_monopole
        }
        (RequestedField::AField, Source::CurrentDensity, MultipoleOrder::Dipole) => {
            a_current_node_dipole
        }
        (RequestedField::HField, Source::CurrentDensity, MultipoleOrder::Monopole) => {
            h_current_node_monopole
        }
        (RequestedField::HField, Source::CurrentDensity, MultipoleOrder::Dipole) => {
            h_current_node_dipole
        }
        (RequestedField::AField, Source::Magnetization, MultipoleOrder::Monopole) => {
            a_mag_node_monopole
        }
        (RequestedField::AField, Source::Magnetization, MultipoleOrder::Dipole) => {
            a_mag_node_dipole
        }
        (RequestedField::HField, Source::Magnetization, MultipoleOrder::Monopole) => {
            h_mag_node_monopole
        }
        (RequestedField::HField, Source::Magnetization, MultipoleOrder::Dipole) => {
            println!(
                r#"Warning. Dipole order expansion not yet defined for H from M sources.
                Defaulting to monopole expansion."#
            );
            h_mag_node_monopole
        }
    }
}

/// Compute the antisymmetric part of the dipole tensor
fn m_from_dipole(dipole: &Mat3) -> Vec3 {
    // m[k] = 0.5 * (M[j,i] - M[i,j])
    Vec3([
        0.5 * (dipole[2][1] - dipole[1][2]),
        0.5 * (dipole[0][2] - dipole[2][0]),
        0.5 * (dipole[1][0] - dipole[0][1]),
    ])
}

/// Compute the vector potential generated by an octree node with current density
/// excitation using a 0th order (monopole) multipole expansion about the centroid
/// of the contained source vectors
pub fn a_current_node_monopole(
    expansion: MultipoleExpansion,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let (x, y, z) = targets;
    let (ax, ay, az) = out;
    let n_targets = check_lengths!(x, y, z, ax, ay, az);
    let c: Vec3 = *expansion.c;
    let p: Vec3 = *expansion.p;

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let rp: Vec3 = target - c;

        let r2: f64 = rp.dot(&rp);
        let inv_r: f64 = 1.0 / r2.sqrt();

        let a = (p * inv_r) * MU0_4PI;
        ax[i] += a[0];
        ay[i] += a[1];
        az[i] += a[2];
    }
}

/// Compute the vector potential generated by an octree node with current density
/// excitation using a 1st order (dipole) multipole expansion about the centroid
/// of the contained source vectors
pub fn a_current_node_dipole(
    expansion: MultipoleExpansion,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let (x, y, z) = targets;
    let (ax, ay, az) = out;
    let n_targets = check_lengths!(x, y, z, ax, ay, az);
    let c: Vec3 = *expansion.c;
    let p: Vec3 = *expansion.p;
    let D: Mat3 = *expansion.D;

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let rp: Vec3 = target - c;

        let r2: f64 = rp.dot(&rp);
        let inv_r: f64 = 1.0 / r2.sqrt();
        let rhat: Vec3 = rp * inv_r;
        let inv_r2: f64 = inv_r * inv_r;

        let a: Vec3 = (p * inv_r + D.mul_vec(&rhat) * inv_r2) * MU0_4PI;
        ax[i] += a[0];
        ay[i] += a[1];
        az[i] += a[2];
    }
}

/// Compute the magnetic field strength generated by an octree node with current density
/// excitation using a 0th order (monopole) multipole expansion about the centroid
/// of the contained source vectors
pub fn h_current_node_monopole(
    expansion: MultipoleExpansion,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let (x, y, z) = targets;
    let (hx, hy, hz) = out;
    let n_targets = check_lengths!(x, y, z, hx, hy, hz);
    let c: Vec3 = *expansion.c;
    let p: Vec3 = *expansion.p;

    for i in 0..n_targets {
        let target = Vec3([x[i], y[i], z[i]]);
        let rp: Vec3 = target - c;

        let r2: f64 = rp.dot(&rp);
        let inv_r: f64 = 1.0 / r2.sqrt();
        let rhat: Vec3 = rp * inv_r;
        let inv_r2: f64 = inv_r * inv_r;

        // Monopole contribution: h += 1/(4*pi) * jv / |rhat|^2
        let h: Vec3 = p.cross(&rhat) * (INV_4PI * inv_r2);
        hx[i] += h[0];
        hy[i] += h[1];
        hz[i] += h[2];
    }
}

/// Compute the magnetic field strength at a series of target points, using both
/// the monopole and dipole terms in the multipole expansion, about the current-weighted
/// centroid of the individual current sources contained in an octree node
pub fn h_current_node_dipole(
    expansion: MultipoleExpansion,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let (x, y, z) = targets;
    let (hx, hy, hz) = out;
    let n_targets = check_lengths!(x, y, z, hx, hy, hz);
    let c: Vec3 = *expansion.c;
    let p: Vec3 = *expansion.p;
    let D: Mat3 = *expansion.D;

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let rp: Vec3 = target - c;

        let r2: f64 = rp.dot(&rp);
        let inv_r: f64 = 1.0 / r2.sqrt();
        let rhat: Vec3 = rp * inv_r;
        let inv_r2: f64 = inv_r * inv_r;
        let inv_r3: f64 = inv_r * inv_r2;

        let m2: Vec3 = m_from_dipole(&D) * 2.0;

        // Monopole contribution: h += 1/(4*pi) * jv / |rhat|^2
        let h_monopole: Vec3 = p.cross(&rhat) * (INV_4PI * inv_r2);

        // Dipole contribution: h += 1/(4pi * |r|^3) * (2m - 3rhat x (M rhat))
        let h_dipole: Vec3 = (m2 - rhat.cross(&D.mul_vec(&rhat)) * 3.0) * (INV_4PI * inv_r3);
        let h: Vec3 = h_monopole + h_dipole;
        hx[i] += h[0];
        hy[i] += h[1];
        hz[i] += h[2];
    }
}

/// Compute the magnetic vector potential at a series of target points, using just
/// the monopole term in the multipole expansion, about the weighted
/// centroid of the individual magnetization sources contained in an octree node
pub fn a_mag_node_monopole(
    expansion: MultipoleExpansion,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    // Note: this is the same as the H from J formulation, just preceded by a
    // multiplication by mu0

    let (x, y, z) = targets;
    let (hx, hy, hz) = out;
    let n_targets = check_lengths!(x, y, z, hx, hy, hz);
    let c: Vec3 = *expansion.c;
    let p: Vec3 = *expansion.p;

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let rp: Vec3 = target - c;

        let r2: f64 = rp.dot(&rp);
        let inv_r: f64 = 1.0 / r2.sqrt();
        let rhat: Vec3 = rp * inv_r;
        let inv_r2: f64 = inv_r * inv_r;

        // Monopole contribution: a += mu0/(4*pi) * jv / |rhat|^2
        let h: Vec3 = p.cross(&rhat) * (MU0_4PI * inv_r2);

        hx[i] += h[0];
        hy[i] += h[1];
        hz[i] += h[2];
    }
}

/// Compute the magnetic vector potential at a series of target points, using both
/// the monopole and dipole terms in the multipole expansion, about the weighted
/// centroid of the individual magnetization sources contained in an octree node
pub fn a_mag_node_dipole(
    expansion: MultipoleExpansion,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    // Note: this is the same as the H from J formulation, just preceded by a
    // multiplication by mu0

    let (x, y, z) = targets;
    let (hx, hy, hz) = out;
    let n_targets = check_lengths!(x, y, z, hx, hy, hz);
    let c: Vec3 = *expansion.c;
    let p: Vec3 = *expansion.p;
    let D: Mat3 = *expansion.D;

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let rp: Vec3 = target - c;

        let r2: f64 = rp.dot(&rp);
        let inv_r: f64 = 1.0 / r2.sqrt();
        let rhat: Vec3 = rp * inv_r;
        let inv_r2: f64 = inv_r * inv_r;
        let inv_r3: f64 = inv_r * inv_r2;

        let m2: Vec3 = m_from_dipole(&D) * 2.0;

        // Monopole contribution: h += 1/(4*pi) * jv / |rhat|^2
        let h_monopole: Vec3 = p.cross(&rhat) * (INV_4PI * inv_r2);

        // Dipole contribution: h += 1/(4pi * |r|^3) * (2m - 3rhat x (M rhat))
        let h_dipole: Vec3 = (m2 - rhat.cross(&D.mul_vec(&rhat)) * 3.0) * (INV_4PI * inv_r3);
        let h: Vec3 = (h_monopole + h_dipole) * MU0;
        hx[i] += h[0];
        hy[i] += h[1];
        hz[i] += h[2];
    }
}

/// Compute the magnetic field strength at a series of target points, using just
/// the monopole term in the multipole expansion, about the weighted
/// centroid of the individual magnetization sources contained in an octree node
pub fn h_mag_node_monopole(
    expansion: MultipoleExpansion,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let (x, y, z) = targets;
    let (hx, hy, hz) = out;
    let n_targets = check_lengths!(x, y, z, hx, hy, hz);
    let c: Vec3 = *expansion.c;
    let p: Vec3 = *expansion.p;

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let rp: Vec3 = target - c;

        let r2: f64 = rp.dot(&rp);
        let inv_r: f64 = 1.0 / r2.sqrt();
        let rhat: Vec3 = rp * inv_r;
        let inv_r2: f64 = inv_r * inv_r;
        let inv_r3: f64 = inv_r * inv_r2;

        // Monopole contribution: h += 1/(4*pi) * (3*rhat*(rhat*p) - p) / |r|^3
        let h: Vec3 = (rhat * 3.0 * rhat.dot(&p) - p) * (INV_4PI * inv_r3);

        hx[i] += h[0];
        hy[i] += h[1];
        hz[i] += h[2];
    }
}
