use crate::types::Vec3;
use crate::{MU0_4PI, check_lengths, mesh};
use std::f64::consts::PI;

const INV_4PI: f64 = 1.0 / (4.0 * PI);

fn sphere_radius(volume: f64) -> f64 {
    ((3.0 / (4.0 * PI)) * volume).cbrt()
}

/// H-field generated by a infinitesimal point current source
///
/// Handles singularities within the point element by providing it finite radius
pub fn h_point(centroid: &Vec3, vj: &Vec3, radius: f64, target: &Vec3) -> Vec3 {
    let r: Vec3 = *target - *centroid;
    let mut vjr: Vec3 = (*vj).cross(&r);
    let rmag: f64 = r.mag();

    if rmag < radius {
        let inside_scale: f64 = (0.25 / PI) * rmag * rmag * rmag / (radius * radius * radius);
        vjr[0] *= inside_scale;
        vjr[1] *= inside_scale;
        vjr[2] *= inside_scale;
    } else {
        let inv_rmag3 = (0.25 / PI) / (rmag * rmag * rmag);
        vjr[0] *= inv_rmag3;
        vjr[1] *= inv_rmag3;
        vjr[2] *= inv_rmag3;
    }

    vjr
}

/// Calculate the magnetic vector potential at a series of target points, using a point
/// approximate of a source with an associated constant current density vector
///
/// This version does NOT handle singularities at the point, as it is designed to be
/// used in the far-field only (away from the source).
///
/// # Args
/// * `centroid`: (m) x,y,z location of the source point
/// * `jmoment`: (A/m^2) current density vector associated with the source point,
///   multiplied by the volume of the source point approximation
/// * `targets`: (m) x,y,z coordinates of the target points
/// * `out`: (T*m) magnetic vector potential at the target points
///
/// # Note
/// This function accumulates into `out`. It is the caller's responsibility to properly
/// zero these arrays.
pub fn a_current_point(
    nodes: &[Vec3; 4],
    jdensity: &Vec3,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let centroid: Vec3 = mesh::centroid(nodes);
    let volume: f64 = mesh::volume(nodes);
    let jmoment: Vec3 = *jdensity * volume;
    let (x, y, z) = targets;
    let (ax, ay, az) = out;
    let n_targets: usize = check_lengths!(x, y, z, ax, ay, az);

    for i in 0..n_targets {
        let target = Vec3([x[i], y[i], z[i]]);
        let rmag: f64 = (target - centroid).mag();
        let a: Vec3 = jmoment * MU0_4PI / rmag;
        ax[i] += a[0];
        ay[i] += a[1];
        az[i] += a[2];
    }
}

pub fn a_mag_point(
    nodes: &[Vec3; 4],
    jdensity: &Vec3,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    panic!("Not implemented yet");
}

/// H-field generated by an infinitesimal point current source, vectorized
/// over target points
///
/// This version does NOT handle singularities at the point, as it is designed
/// to be used in the far-field only (away from the source)
pub fn h_current_point(
    nodes: &[Vec3; 4],
    jdensity: &Vec3,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let centroid: Vec3 = mesh::centroid(nodes);
    let volume: f64 = mesh::volume(nodes);
    let radius = sphere_radius(volume);
    let jmoment: Vec3 = *jdensity * volume;
    let (x, y, z) = targets;
    let (hx, hy, hz) = out;
    let n_targets: usize = check_lengths!(x, y, z, hx, hy, hz);
    let radius_cubed = radius.powi(3);

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let r: Vec3 = target - centroid;
        let rmag: f64 = r.mag();
        let r3: f64 = rmag.powi(3);
        let constant: f64 = 1.0 / r3.max(radius_cubed);
        let vjr: Vec3 = (jmoment).cross(&r);
        let h: Vec3 = vjr * constant * INV_4PI;
        hx[i] += h[0];
        hy[i] += h[1];
        hz[i] += h[2];
    }
}

/// H-field generated by an infinitesimal point dipole source, vectorized over target
/// points
///
/// For now, applies zero field to internal points. The use of this function should be limited
/// to self (zero) or adjacent elements in the mesh, not arbitrary points in the mesh domain.
/// TODO: Use the internal-sphere correction provided in ex 6.1 of griffith's:
/// <https://peppyhare.github.io/griffiths-em/ch6-2/>
/// and in Fitzpatrick:
/// <https://farside.ph.utexas.edu/teaching/jk1/Electromagnetism/node61.html>
#[inline]
pub fn h_mag_point(
    nodes: &[Vec3; 4],
    magnetization: &Vec3,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let centroid: Vec3 = mesh::centroid(nodes);
    let volume: f64 = mesh::volume(nodes);
    let radius: f64 = sphere_radius(volume);
    let moment: Vec3 = *magnetization * volume;
    let (x, y, z) = targets;
    let (hx, hy, hz) = out;
    let n_targets: usize = check_lengths!(x, y, z, hx, hy, hz);

    for i in 0..n_targets {
        let target: Vec3 = Vec3([x[i], y[i], z[i]]);
        let r = target - centroid;
        let rmag = r.mag();
        let h_field: Vec3;

        if rmag <= radius {
            // Internal magnetization field provided by the dipole moment at `radius`
            // TODO: should this just be
            let m_field: Vec3 = moment * (3.0 / (4.0 * PI * radius.powi(3)));
            h_field = m_field * (-1.0 / 3.0);
        } else {
            // outside the sphere
            let rmag_inv: f64 = 1.0 / rmag;
            let rhat: Vec3 = r * rmag_inv;
            let scale: f64 = INV_4PI * rmag_inv.powi(3);
            h_field = ((rhat * (3.0 * rhat.dot(&moment))) - moment) * scale;
        }

        hx[i] += h_field[0];
        hy[i] += h_field[1];
        hz[i] += h_field[2];
    }
}
