use crate::types::Vec3;
use crate::{MU0_4PI, check_lengths};
use std::f64::consts::PI;

const INV_4PI: f64 = 1.0 / (4.0 * PI);

/// H-field generated by a infinitesimal point current source
///
/// Handles singularities within the point element by providing it finite radius
pub fn h_point(centroid: &Vec3, vj: &Vec3, radius: f64, target: &Vec3) -> Vec3 {
    let r: Vec3 = *target - *centroid;
    let mut vjr: Vec3 = (*vj).cross(&r);
    let rmag: f64 = r.mag();

    if rmag < radius {
        let inside_scale: f64 = (0.25 / PI) * rmag * rmag * rmag / (radius * radius * radius);
        vjr[0] *= inside_scale;
        vjr[1] *= inside_scale;
        vjr[2] *= inside_scale;
    } else {
        let inv_rmag3 = (0.25 / PI) / (rmag * rmag * rmag);
        vjr[0] *= inv_rmag3;
        vjr[1] *= inv_rmag3;
        vjr[2] *= inv_rmag3;
    }

    vjr
}

/// Calculate the magnetic vector potential at a series of target points, using a point
/// approximate of a source with an associated constant current density vector
///
/// This version does NOT handle singularities at the point, as it is designed to be
/// used in the far-field only (away from the source).
///
/// # Args
/// * `centroid`: (m) x,y,z location of the source point
/// * `jmoment`: (A/m^2) current density vector associated with the source point,
///   multiplied by the volume of the source point approximation
/// * `targets`: (m) x,y,z coordinates of the target points
/// * `out`: (T*m) magnetic vector potential at the target points
///
/// # Note
/// This function accumulates into `out`. It is the caller's responsibility to properly
/// zero these arrays.
pub fn a_current_point(
    centroid: &Vec3,
    jmoment: &Vec3,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let (x, y, z) = targets;
    let (ax, ay, az) = out;
    let n_targets: usize = check_lengths!(x, y, z, ax, ay, az);

    for i in 0..n_targets {
        let target = Vec3([x[i], y[i], z[i]]);
        let rmag: f64 = (target - *centroid).mag();
        let a: Vec3 = *jmoment * MU0_4PI / rmag;
        ax[i] += a[0];
        ay[i] += a[1];
        az[i] += a[2];
    }
}

/// H-field generated by an infinitesimal point current source, vectorized
/// over target points
///
/// This version does NOT handle singularities at the point, as it is designed
/// to be used in the far-field only (away from the source)
pub fn h_current_point(
    centroid: &Vec3,
    vj: &Vec3,
    targets: (&[f64], &[f64], &[f64]),
    out: (&mut [f64], &mut [f64], &mut [f64]),
) {
    let (tx, ty, tz) = targets;
    let (hx, hy, hz) = out;
    let n_targets: usize = check_lengths!(tx, ty, tz, hx, hy, hz);

    for i in 0..n_targets {
        let target: Vec3 = Vec3([tx[i], ty[i], tz[i]]);
        let r: Vec3 = target - *centroid;
        let vjr: Vec3 = (*vj).cross(&r);
        let rmag: f64 = r.mag();
        let h: Vec3 = vjr * INV_4PI / (rmag * rmag * rmag);
        hx[i] += h[0];
        hy[i] += h[1];
        hz[i] += h[2];
    }
}

/// H-field generated by an infinitesimal point dipole source
///
/// For now, applies zero field to internal points. The use of this function should be limited
/// to self (zero) or adjacent elements in the mesh, not arbitrary points in the mesh domain.
/// TODO: Use the internal-sphere correction provided in ex 6.1 of griffith's:
/// <https://peppyhare.github.io/griffiths-em/ch6-2/>
/// and in Fitzpatrick:
/// <https://farside.ph.utexas.edu/teaching/jk1/Electromagnetism/node61.html>
#[inline]
pub fn h_point_dipole(centroid: &Vec3, moment: &Vec3, radius: f64, target: &Vec3) -> Vec3 {
    let r = *target - *centroid;
    let rmag = r.mag();

    if rmag <= radius {
        // Internal magnetization field provided by the dipole moment at `radius`
        let m_field = *moment * (3.0 / (4.0 * PI * radius.powi(3)));
        let h_field = m_field * (-1.0 / 3.0);
        return h_field;
    }

    // outside the sphere
    let rmag_inv: f64 = 1.0 / rmag;
    let rhat: Vec3 = r * rmag_inv;

    let scale: f64 = INV_4PI * rmag_inv.powi(3);
    ((rhat * (3.0 * rhat.dot(moment))) - *moment) * scale
}
